#!/bin/bash
#reset tables
/sbin/iptables -t mangle -F FORWARD
/sbin/ip6tables -t mangle -F FORWARD
/sbin/iptables -t mangle -F OUTPUT
/sbin/ip6tables -t mangle -F OUTPUT
#tcp ack,sync - do not police
/sbin/ip6tables -t mangle -A FORWARD -o enxa0cec8092605 -p tcp -m length --length 0:128 -j MARK --set-xmark 0x2/0xffffffff
/sbin/iptables -t mangle -A FORWARD -o enxa0cec8092605 -p tcp -m length --length 0:128 -j MARK --set-xmark 0x2/0xffffffff
#ef
/sbin/ip6tables -t mangle -A FORWARD -o enxa0cec8092605 -m dscp --dscp 0x2e -j MARK --set-xmark 0x2/0xffffffff
/sbin/iptables -t mangle -A FORWARD -o enxa0cec8092605 -m dscp --dscp 0x2e -j MARK --set-xmark 0x2/0xffffffff
#TODO: this need refine but all udp
/sbin/ip6tables -t mangle -A FORWARD -o enxa0cec8092605 -p udp -j MARK --set-xmark 0x2/0xffffffff
/sbin/iptables -t mangle -A FORWARD -o enxa0cec8092605 -p udp -j MARK --set-xmark 0x2/0xffffffff
#following too are just counters for telegraf to pick up
/sbin/ip6tables -t mangle -A FORWARD -o enxa0cec8092605 -m mark ! --mark 0x2 -m comment --comment "ip6-non-mark-2"
/sbin/ip6tables -t mangle -A FORWARD -o enxa0cec8092605 -m mark --mark 0x2 -m comment --comment "ip6-mark-2"
/sbin/iptables -t mangle -A FORWARD -o enxa0cec8092605 -m mark ! --mark 0x2 -m comment --comment "ip4-non-mark-2"
/sbin/iptables -t mangle -A FORWARD -o enxa0cec8092605 -m mark --mark 0x2 -m comment --comment "ip4-mark-2"
#inbound -limit the tcp it's reserve to outbound
/sbin/ip6tables -t mangle -A FORWARD -i enxa0cec8092605 -p tcp -m tcp -j MARK --set-xmark 0x3e7/0xffffffff
/sbin/iptables -t mangle -A FORWARD -i enxa0cec8092605 -p tcp -m tcp -j MARK --set-xmark 0x3e7/0xffffffff
#do not police DNS
/sbin/ip6tables -t mangle -A OUTPUT -p udp -m udp --dport 53 -j MARK --set-xmark 0x2/0xffffffff
/sbin/iptables -t mangle -A OUTPUT -p udp -m udp --dport 53 -j MARK --set-xmark 0x2/0xffffffff
#do not police DHCP
/sbin/ip6tables -t mangle -A OUTPUT -p udp -m udp --sport 547 --dport 546 -j MARK --set-xmark 0x2/0xffffffff
/sbin/iptables -t mangle -A OUTPUT -p udp -m udp --sport 67:68 --dport 67:68 -j MARK --set-xmark 0x2/0xffffffff

